import React from 'react';
import './index.css';

function App() {
  return (
    <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center">
      <h1 className="text-4xl font-bold text-gray-800">
        Welcome to ryzha 🧭
      </h1>
      <p className="text-gray-500 mt-2">
        Generated by Navi - Your project is ready!
      </p>
    </div>
  );
}

export default App;
